[phases.build]
# Build the Node.js frontend (located in the TravelFrontend folder)

# Build the Spring Boot backend (located in the backend folder)
backend = "cd backend && mvn clean package"

[phases.start]
# Start the Spring Boot backend
backend = "cd backend && java -jar target/*.jar"

# Serve the Node.js frontend (if needed)

[env]
# Environment variables for both frontend and backend
NODE_ENV = "production"
SPRING_PROFILES_ACTIVE = "prod"

[files]
# Include necessary files for both frontend and backend
"backend/" = "backend"

[ports]
# Expose the necessary ports
backend = 8080  # Spring Boot backend port
