spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/traveldb
      #host: localhost
      #port: 27017
      #database: traveldb

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              org.springframework.data.mongodb.core.MongoTemplate: INFO

security:
  jwt:
    secret: 'someSecretKey'